# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/drew/study/lab3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/drew/study/lab3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drew/study/lab3/CMakeFiles /home/drew/study/lab3//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drew/study/lab3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lab_objects

# Build rule for target.
lab_objects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab_objects
.PHONY : lab_objects

# fast build rule for target.
lab_objects/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab_objects.dir/build.make CMakeFiles/lab_objects.dir/build
.PHONY : lab_objects/fast

#=============================================================================
# Target rules for targets named lib_objects

# Build rule for target.
lib_objects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_objects
.PHONY : lib_objects

# fast build rule for target.
lib_objects/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_objects.dir/build.make CMakeFiles/lib_objects.dir/build
.PHONY : lib_objects/fast

#=============================================================================
# Target rules for targets named compile

# Build rule for target.
compile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compile
.PHONY : compile

# fast build rule for target.
compile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compile.dir/build.make CMakeFiles/compile.dir/build
.PHONY : compile/fast

#=============================================================================
# Target rules for targets named lab

# Build rule for target.
lab: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab
.PHONY : lab

# fast build rule for target.
lab/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/build
.PHONY : lab/fast

#=============================================================================
# Target rules for targets named ipv4

# Build rule for target.
ipv4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ipv4
.PHONY : ipv4

# fast build rule for target.
ipv4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ipv4.dir/build.make CMakeFiles/ipv4.dir/build
.PHONY : ipv4/fast

#=============================================================================
# Target rules for targets named build

# Build rule for target.
build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build
.PHONY : build

# fast build rule for target.
build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/build
.PHONY : build/fast

#=============================================================================
# Target rules for targets named scp

# Build rule for target.
scp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scp
.PHONY : scp

# fast build rule for target.
scp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scp.dir/build.make CMakeFiles/scp.dir/build
.PHONY : scp/fast

#=============================================================================
# Target rules for targets named env

# Build rule for target.
env: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 env
.PHONY : env

# fast build rule for target.
env/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/env.dir/build.make CMakeFiles/env.dir/build
.PHONY : env/fast

#=============================================================================
# Target rules for targets named super_clean

# Build rule for target.
super_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 super_clean
.PHONY : super_clean

# fast build rule for target.
super_clean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/super_clean.dir/build.make CMakeFiles/super_clean.dir/build
.PHONY : super_clean/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named music

# Build rule for target.
music: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 music
.PHONY : music

# fast build rule for target.
music/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/music.dir/build.make CMakeFiles/music.dir/build
.PHONY : music/fast

src/lab1aotN3246.o: src/lab1aotN3246.c.o
.PHONY : src/lab1aotN3246.o

# target to build an object file
src/lab1aotN3246.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab_objects.dir/build.make CMakeFiles/lab_objects.dir/src/lab1aotN3246.c.o
.PHONY : src/lab1aotN3246.c.o

src/lab1aotN3246.i: src/lab1aotN3246.c.i
.PHONY : src/lab1aotN3246.i

# target to preprocess a source file
src/lab1aotN3246.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab_objects.dir/build.make CMakeFiles/lab_objects.dir/src/lab1aotN3246.c.i
.PHONY : src/lab1aotN3246.c.i

src/lab1aotN3246.s: src/lab1aotN3246.c.s
.PHONY : src/lab1aotN3246.s

# target to generate assembly for a file
src/lab1aotN3246.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab_objects.dir/build.make CMakeFiles/lab_objects.dir/src/lab1aotN3246.c.s
.PHONY : src/lab1aotN3246.c.s

src/libaotN3246.o: src/libaotN3246.c.o
.PHONY : src/libaotN3246.o

# target to build an object file
src/libaotN3246.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_objects.dir/build.make CMakeFiles/lib_objects.dir/src/libaotN3246.c.o
.PHONY : src/libaotN3246.c.o

src/libaotN3246.i: src/libaotN3246.c.i
.PHONY : src/libaotN3246.i

# target to preprocess a source file
src/libaotN3246.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_objects.dir/build.make CMakeFiles/lib_objects.dir/src/libaotN3246.c.i
.PHONY : src/libaotN3246.c.i

src/libaotN3246.s: src/libaotN3246.c.s
.PHONY : src/libaotN3246.s

# target to generate assembly for a file
src/libaotN3246.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_objects.dir/build.make CMakeFiles/lib_objects.dir/src/libaotN3246.c.s
.PHONY : src/libaotN3246.c.s

testSrc/test.o: testSrc/test.c.o
.PHONY : testSrc/test.o

# target to build an object file
testSrc/test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/testSrc/test.c.o
.PHONY : testSrc/test.c.o

testSrc/test.i: testSrc/test.c.i
.PHONY : testSrc/test.i

# target to preprocess a source file
testSrc/test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/testSrc/test.c.i
.PHONY : testSrc/test.c.i

testSrc/test.s: testSrc/test.c.s
.PHONY : testSrc/test.s

# target to generate assembly for a file
testSrc/test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/testSrc/test.c.s
.PHONY : testSrc/test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... build"
	@echo "... compile"
	@echo "... env"
	@echo "... music"
	@echo "... scp"
	@echo "... super_clean"
	@echo "... ipv4"
	@echo "... lab"
	@echo "... lab_objects"
	@echo "... lib_objects"
	@echo "... test"
	@echo "... src/lab1aotN3246.o"
	@echo "... src/lab1aotN3246.i"
	@echo "... src/lab1aotN3246.s"
	@echo "... src/libaotN3246.o"
	@echo "... src/libaotN3246.i"
	@echo "... src/libaotN3246.s"
	@echo "... testSrc/test.o"
	@echo "... testSrc/test.i"
	@echo "... testSrc/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

